---
    name: Build Node
    on:
      workflow_call:
        inputs:
          collectCoverage:
            required: false
            type: boolean
            default: false

          skip:
            type: boolean
            required: false
            default: false
            description: should the steps be skipped


    jobs:
      compile:
        timeout-minutes: 10
        if: ${{ always() && ! inputs.skip}}
        runs-on: ubuntu-24.04
        permissions:
          contents: read
        steps:
          - uses: actions/checkout@v5
            with:
              show-progress: false
          - uses: actions/setup-node@v6
            with:
              node-version: "20"
              cache: 'yarn'
          - run: yarn install --immutable
          - run: yarn compile
      lint:
        timeout-minutes: 5
        if: ${{ ! inputs.skip && needs.compile.result == 'success'}}
        runs-on: ubuntu-24.04
        needs: [compile]
        permissions:
          contents: read
        steps:
          - uses: actions/checkout@v5
            with:
              show-progress: false
              fetch-depth: 0
          - uses: actions/setup-node@v6
            with:
              node-version: "20"
              cache: 'yarn'
          - run: yarn install --immutable
          - run: yarn lint
      test:
        timeout-minutes: 10
        if: ${{ ! inputs.skip && needs.compile.result == 'skipped'  }}
        needs: [compile]
        runs-on: 'ubuntu-24.04'
        permissions:
          contents: read
        steps:
          - uses: actions/checkout@v5
            with:
              show-progress: false
          - uses: actions/setup-node@v6
            with:
              node-version: "20"
              cache: 'yarn'
          - run: yarn install --immutable
          - run: yarn test